CREATE TABLE `employee` (
`id` INT NOT NULL AUTO_INCREMENT ,
`companyProfileId` varchar(128) NOT NULL COMMENT 'Enter companyProfileId',
`TrainingInfo` varchar(128) DEFAULT NULL COMMENT 'Enter TrainingInfo',
`EmpDocInfo` varchar(128) DEFAULT NULL COMMENT 'Enter EmpDocInfo',
`applicantId` varchar(128) DEFAULT NULL COMMENT 'Enter applicantId',
`firstName` varchar(128) DEFAULT NULL COMMENT 'Enter firstName',
`lastName` varchar(128) DEFAULT NULL COMMENT 'Enter lastName',
`fatherName` varchar(128) DEFAULT NULL COMMENT 'Enter fatherName',
`motherName` varchar(128) DEFAULT NULL COMMENT 'Enter motherName',
`spouseName` varchar(128) DEFAULT NULL COMMENT 'Enter spouseName',
`nationality` varchar(128) DEFAULT NULL COMMENT 'Enter nationality',
`gender` varchar(128) DEFAULT NULL COMMENT 'Enter gender',
`age` varchar(128) DEFAULT NULL COMMENT 'Enter age',
`profilePic` varchar(128) DEFAULT NULL COMMENT 'Enter profilePic',
`signature` varchar(128) DEFAULT NULL COMMENT 'Enter signature',
`nidImage` varchar(128) DEFAULT NULL COMMENT 'Enter nidImage',
`eduQualification` varchar(128) DEFAULT NULL COMMENT 'Enter eduQualification',
`bloodGroup` varchar(128) DEFAULT NULL COMMENT 'Enter bloodGroup',
`religion` varchar(128) DEFAULT NULL COMMENT 'Enter religion',
`address` varchar(128) DEFAULT NULL COMMENT 'Enter address',
`streetAddress` varchar(128) DEFAULT NULL COMMENT 'Enter streetAddress',
`district` varchar(128) DEFAULT NULL COMMENT 'Enter district',
`policeStation` varchar(128) DEFAULT NULL COMMENT 'Enter policeStation',
`postCode` varchar(128) DEFAULT NULL COMMENT 'Enter postCode',
`chairmanName` varchar(128) DEFAULT NULL COMMENT 'Enter chairmanName',
`contactNo` varchar(128) DEFAULT NULL COMMENT 'Enter contactNo',
`email` varchar(128) DEFAULT NULL COMMENT 'Enter email',
`managerId` varchar(128) DEFAULT NULL COMMENT 'Enter managerId',
`isDeleted` tinyint(4) NOT NULL DEFAULT '0',
`isApproved` tinyint(4) NOT NULL DEFAULT '0',
  `createdBy` int(11) NOT NULL,
  `createdDate` datetime NOT NULL,
  `updatedBy` int(11) DEFAULT NULL,
  `updatedDate` datetime DEFAULT NULL,
PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;