CREATE TABLE `front_page` (
`id` INT NOT NULL AUTO_INCREMENT ,
`title` varchar(128) DEFAULT NULL COMMENT 'Enter title',
`heading` varchar(128) NOT NULL COMMENT 'Enter heading',
`headline` varchar(128) DEFAULT NULL COMMENT 'Enter headline',
`description` varchar(128) DEFAULT NULL COMMENT 'Enter description',
`specialLink` varchar(128) DEFAULT NULL COMMENT 'Enter specialLink',
`linkType` varchar(128) DEFAULT NULL COMMENT 'Enter linkType',
`detailsLink` varchar(128) DEFAULT NULL COMMENT 'Enter detailsLink',
`detailsLinkText` varchar(128) NOT NULL COMMENT 'Enter detailsLinkText',
`contactUsHeadline` varchar(128) DEFAULT NULL COMMENT 'Enter contactUsHeadline',
`footerMessage` varchar(128) DEFAULT NULL COMMENT 'Enter footerMessage',
`footerLink` varchar(128) DEFAULT NULL COMMENT 'Enter footerLink',
`facebookLink` varchar(128) DEFAULT NULL COMMENT 'Enter facebookLink',
`githubLink` varchar(128) DEFAULT NULL COMMENT 'Enter githubLink',
`twitterLink` varchar(128) DEFAULT NULL COMMENT 'Enter twitterLink',
`linkedInLink` varchar(128) DEFAULT NULL COMMENT 'Enter linkedInLink',
`Features` varchar(128) DEFAULT NULL COMMENT 'Enter Features',
`Characteristics` varchar(128) DEFAULT NULL COMMENT 'Enter Characteristics',
`Projects` varchar(128) DEFAULT NULL COMMENT 'Enter Projects',
`PricingPlan` varchar(128) DEFAULT NULL COMMENT 'Enter PricingPlan',
`Team` varchar(128) DEFAULT NULL COMMENT 'Enter Team',
`isDeleted` tinyint(4) NOT NULL DEFAULT '0',
`isApproved` tinyint(4) NOT NULL DEFAULT '0',
  `createdBy` int(11) NOT NULL,
  `createdDate` datetime NOT NULL,
  `updatedBy` int(11) DEFAULT NULL,
  `updatedDate` datetime DEFAULT NULL,
PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;